### ISSUE TITLE
all the scrollbar modification has stopped working for newest chrome

### ISSUE THREAD

**Issue by minkoonim** [unpreset/unocss-preset-scrollbar#12]
In Edge, It works fine.

using chrome 122.0.6261.6 beta,
I don't know since which version,
but all the pretty scrollbar has changed to original ugly ones.

below is official demo on chrome
![image](https://github.com/unpreset/unocss-preset-scrollbar/assets/38183949/43216cfd-2f25-4da6-895a-96badb977787)

**Comment by minkoonim** [comment]
https://stackoverflow.com/questions/77884029/customize-scrollbar-webkit-scrollbar-not-working-in-version-121-0-6167-86

https://developer.chrome.com/blog/new-in-chrome-121#css-updates

**Comment by action-hong** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar

> The ::-webkit-scrollbar vendor-prefixed pseudo-element is not supported on all browsers (see [Browser compatibility](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar#browser_compatibility)). The [scrollbar-color](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color) and [scrollbar-width](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width) standard properties may be used as an alternative for browsers that do not support this pseudo-element. When these properties are set, ::-webkit-scrollbar styling is disabled.

The original code generate `scrollbar-color: xxxx`, causing ::-webkit-scrollbar styling is disabled.

---

i try to add a config `noCompatible` to fix it #13 

if `true`, remove `scrollbar-color` in the generate code, and it works fine like before

if `false`, use `scrollbar-color` and `scrollbar-width`, and it can works in firefox too, but can not use `scrollbar-(w|h|radius)` to set scrollbar thumb, track size

---


Do you have any suggestions or a better solution? @minkoonim
