### ISSUE TITLE
 WARN  [unocss] unmatched utility "scrollbar-color-[var(--scrollbar-thumb)_var(--scrollbar-track)]" in shortcut "scrollbar"        14:27:38

### ISSUE THREAD

**Issue by zyhnbyyds** [unpreset/unocss-preset-scrollbar#14]
![image](https://github.com/unpreset/unocss-preset-scrollbar/assets/83394286/cac12c69-a9e7-4f12-b613-7c342f3aa4c0)

**Comment by zyhnbyyds** [comment]
![image](https://github.com/unpreset/unocss-preset-scrollbar/assets/83394286/56dcc060-48a0-4b14-ae33-60e3ef247145)

**Comment by action-hong** [comment]
it should be `dark:track-color-[#1a1a1a]` not `dark:track-color-[bg-#1a1a1a]`

---

```
[unocss] unmatched utility "scrollbar-width-thin" in shortcut "scrollbar-thin"
[unocss] unmatched utility "scrollbar-width-auto" in shortcut "scrollbar"
[unocss] unmatched utility "scrollbar-color-[var(--scrollbar-thumb)_var(--scrollbar-track)]" in shortcut "scrollbar"
```

Looks like a useless utility was generated, I'll get rid of it as soon as possible

**Comment by zyhnbyyds** [comment]
sorry, my bad. Next time i will check the docs clearly. 🫡🫡
