### ISSUE TITLE
UnPreset invitation

### ISSUE THREAD

**Issue by zyyv** [unpreset/unocss-preset-scrollbar#9]
Thanks for this great preset, it works great for me. 
I sent you an organizational invitation and I see you accepted it.
You can `transfer` this repository to the `unpreset` organization in your free time and I will assign permissions to you.
Thanks again.

**Comment by action-hong** [comment]
Ok&nbsp;
i will do it next day free time



发自我的iPhone


------------------ Original ------------------
From: Chris ***@***.***&gt;
Date: Sun,Sep 10,2023 8:14 PM
To: action-hong/unocss-preset-scrollbar ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [action-hong/unocss-preset-scrollbar] UnPreset invitation (Issue #9)





 
Thanks for this great preset, it works great for me.
 I sent you an organizational invitation and I see you accepted it.
 You can transfer this repository to the unpreset organization in your free time and I will assign permissions to you.
 Thanks again.
